server 10.0.0.10 

(de momento al ser CLI y no poder copiar el contenido exacto del archivo, pondré solo lo que añadi, fue necesario también comentar la linea que viene por defecto definiendo **pool**)
